def runInDocker(String image, Closure body) {
  // TODO (E4): Ejecuta `body()` dentro del contenedor indicado usando Docker Pipeline:
   docker.image(image).inside { body() }
}
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  /*agent {
    docker { 
        image 'python:3.6-slim'
        args '-u root' 
    }
  }*/

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
    /*stage('Prepare') {
       steps {
          sh 'apt-get update && apt-get install -y make'
          sh 'pip install -r requirements.txt flake8 mypy'
       }
    }*/
    stage('CI - Lint') {
      steps {
         runInDocker('python:3.6-slim') {
           sh 'apt-get update && apt-get install -y make'
           sh 'make lint'
         }  
      }
    }
    stage('CI - Test') {
      steps {
         runInDocker('python:3.6-slim') { 
           h 'pytest -q'
         }  
      }
    }
  }
} 
