/*def runInDocker(String image, Closure body) {
  // TODO (E4): Ejecuta `body()` dentro del contenedor indicado usando Docker Pipeline:
   docker.image(image).inside { body() }
}*/
@Library('iac-devops-lib@feat/base') _
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  parameters {
    booleanParam(name: 'RUN_CD', defaultValue: false, description: 'Ejecutar CD') 
  } 

  environment {
    PYTHON_IMAGE = 'python:3.6-slim'
    IMAGE_REPO_LOCAL = 'devops-training-python-app'
  }

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
    
    stage('Versioning') {
      steps {
        script {
          env.PYTHON_IMAGE = "1.0.${env.BUILD_NUMBER}"
          env.VERSION_JAR = "${env.PYTHON_IMAGE}-SNAPSHOT"
          env.IMAGE_LOCAL = "${env.IMAGE_REPO_LOCAL}:${env.IMAGE_VERSION}"
        }
      }
    }
    
    stage('CI - Test') {
      steps {
        script {
          devopsLib.runInDocker(env.PYTHON_IMAGE) {
            sh 'python --version'
            sh 'pip install -r requirements.txt'
            sh 'pytest -q'
          }
        }
      }
    }
    stage('CI - Build image') {
      steps {
        script {
           env.IMAGE_NAME = "devops-training-python-app:${env.BUILD_NUMBER}"
           docker.build(env.IMAGE_NAME, "-f devops/Dockerfile .")
        }
      }
    }
    stage('CD') {
        when {
          allOf {
            anyOf {
              branch 'develop'
              branch 'main'
            }
            expression { return params.RUN_CD }
          }
        }
        steps {
          script {
            // Definir entorno de despliegue
            echo "CD habilitado: RUN_CD=${params.RUN_CD}, branch=${env.BRANCH_NAME}"  
            env.DEPLOY_ENV = (env.BRANCH_NAME == 'main') ? 'PRO' : 'DEV'
            echo "Deploy env: ${env.DEPLOY_ENV}"
      
            try {
              sh 'docker compose up -d'
              sh 'sleep 5'
              sh 'docker compose logs app'
            } finally {
              sh 'docker compose down --volumes'
            }
          }
        }
        post {
          always {
            echo "Cleanup done"
          }
          success { echo 'SUCCESS' }
          failure { 
             echo 'FAILURE' 
             sh 'docker compose logs || true'
          }
        }
      }
  }
}
  
