def runInDocker(String image, Closure body) {
  // TODO (E4): Ejecuta `body()` dentro del contenedor indicado usando Docker Pipeline:
   docker.image(image).inside { body() }
}
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  /*agent {
    docker { 
        image 'python:3.6-slim'
        args '-u root' 
    }
  }*/

  stages {
    stage('Info') {
      steps {
        echo "Job: ${env.JOB_NAME}"
        echo "Build: ${env.BUILD_NUMBER}"
      }
    }
    stage('CI - Test') {
      steps {
        script {
          runInDocker('python:3.6-slim') {
            sh 'python --version'
            sh 'pip install -r requirements.txt'
            sh 'pytest -q'
          }
        }
      }
    }
  }
}
  
