version: "3.8"

services:
  app:
    image: ${IMAGE_NAME}
    container_name: my-flask-app-dc
    restart: unless-stopped
    networks:
      - scalian_training
    environment:
      DB_USER: root
      DB_PWD: rootpwd
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knights
    depends_on:
      - db
    ports:
      - "5001:5000"

  azp-agent:
    image: mcr.microsoft.com/azure-pipelines/vsts-agent:latest
    restart: unless-stopped
    environment:
      AZP_URL: "https://dev.azure.com/jtomas210"
      AZP_TOKEN: "${AZP_TOKEN}"
      AZP_POOL: "Default"
      AZP_AGENT_NAME: "UNED2"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - python-project-net

  db:
    image: postgres:16-alpine
    container_name: my-flask-app-db
    restart: always
    ports:
      - "32000:5432"
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
      POSTGRES_DB: knights
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      - scalian_training

networks:
  python-project-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.234.0/24  # Rango de subred correcto
          gateway: 172.20.234.1     # Opcional: define el gateway si lo necesitas
  scalian_training:
    driver: bridge

volumes:
  dbdata:
