version: "3.7"

services:
  app:
    #image: jtomaschico/devops-training-python-app:0.0.1
    image: ${IMAGE_NAME}
    #build: 
    #  context: .
    #  dockerfile: devops/Dockerfile
    container_name: my-flask-app-dc
    restart: unless-stopped
    networks:
      - scalian_training
    environment:
      DB_USER: root
      DB_PWD: rootpwd
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: knights
    depends_on:
      - db
    ports:
      - "5001:5000"

  azp-agent:
    image: mcr.microsoft.com/azure-pipelines/vsts-agent:latest  # Imagen del agente de Azure Pipelines
    restart: unless-stopped
    environment:
      AZP_URL: "https://dev.azure.com/jtomas210"  # URL de tu organización de Azure DevOps
      AZP_TOKEN: "${AZP_TOKEN}"  # Asegúrate de definir este token en tus variables de entorno o .env
      AZP_POOL: "Default"  # El nombre de tu pool de agentes
      AZP_AGENT_NAME: "UNED2"  # Nombre de tu agente
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite ejecutar Docker desde el agente
    networks:
      - java-project-net  # Red externa donde están Artifactory, Docker registry, etc.       

  
  db:
    image: postgres:16-alpine
    container_name: my-flask-app-db
    restart: always
    ports:
      - "32000:5432"
    environment:
      POSTGRES_PASSWORD: rootpwd
      POSTGRES_USER: root
      POSTGRES_DB: knights
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    networks:
      scalian_training:

networks:
  scalian_training:
    driver: bridge
  
volumes:

  dbdata:




