trigger:
  branches:
    include:
      - develop
      - main
pr:
  branches:
    include:
      - develop
      - main

resources:
  repositories:
    - repository: iac
      type: github
      name: jtomaschico/devops-training-iac-devops
      ref: refs/heads/feat/base
      endpoint: jtomaschico

variables:
  - group: josetoCredentials
  - name: IMAGE_NAME
    value: "scalian_training-python-app"
  - name: APP_URL
    value: "http://localhost:8084/hello"  # Define tu URL de aplicación o cualquier otra variable relevante

parameters:
  - name: RUN_CD
    type: boolean
    default: false
    displayName: "Run Continuous Deployment"

  - name: DEPLOY_ENV
    type: string
    default: DEV
    displayName: "Deployment Environment"

pool:
  name: Default   # Self-hosted agent

steps:
  - script: |
      echo "Repo:   $(Build.Repository.Name)"
      echo "Branch: $(Build.SourceBranchName)"
      echo "SHA:    $(Build.SourceVersion)"
    displayName: "Info (dummy)"
