trigger:
  branches:
    include:
      - develop
      - main

pr:
  branches:
    include:
      - develop
      - main

resources:
  repositories:
    - repository: iac
      type: github
      name: jtomaschico/devops-training-iac-devops
      ref: refs/heads/feat/base
      endpoint: jtomaschico

variables:
  - group: josetoCredentials
  - name: IMAGE_NAME
    value: "scalian_training-python-app"
  - name: APP_URL
    value: "http://localhost:8084/hello"

parameters:
  - name: RUN_CD
    type: boolean
    default: false
    displayName: "Run Continuous Deployment"

  - name: DEPLOY_ENV
    type: string
    default: DEV
    displayName: "Deployment Environment"

pool:
  name: Default

stages:
  - stage: CI
    displayName: "Continuous Integration"
    jobs:
      - job: Info
        displayName: "Info devops-training-python-app"
        steps:
          - script: |
              echo "Repo:   $(Build.Repository.Name)"
              echo "Branch: $(Build.SourceBranchName)"
              echo "SHA:    $(Build.SourceVersion)"
              echo "Reason: $(Build.Reason)"
              echo "IMAGE: $(IMAGE_NAME)"
              echo "URL:   $(APP_URL)"
            displayName: "Show Info"

      - job: CI_Template
        displayName: "CI Python (template)"
        steps:
          - template: azure-pipelines/templates/ci-python-steps.yml@iac

      - job: Build_Docker_Image
        displayName: "Build Docker Image"
        dependsOn: CI_Template
        steps:
          - checkout: self
          - script: |
              echo "Building Docker image..."
              docker build \
                --build-arg VERSION=$(Build.BuildNumber) \
                -t $(IMAGE_NAME):latest \
                -f devops/Dockerfile .
            displayName: "Docker Build"

  - stage: CD   # ✅ CORREGIDO (alineación)
    displayName: "Continuous Deployment"
    dependsOn: CI
    condition: eq(${{ parameters.RUN_CD }}, true)   # ✅ CORREGIDO
    jobs:
      - job: deploy
        displayName: "Deploy (simulado) + E2E"
        steps:
          - checkout: self

          - script: |
              docker compose up -d
            displayName: "Levantar servicios"

          - script: |
              sleep 5
            displayName: "Esperar a que la app esté lista"

          - script: |
              curl -fsS $(APP_URL)
            displayName: "Test E2E con curl"

          - script: |
              docker compose down --volumes || true
              docker rmi $(IMAGE_NAME) || true
              echo "TODO: cleanup"
            displayName: "Cleanup"
            condition: always()
